name: notification_mode
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://github.com/longtn-imt/notification_mode

environment:
  sdk: ">=3.3.2 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.longtn.notification_mode
        pluginClass: NotificationModePlugin
      ios:
        pluginClass: NotificationModePlugin
